name: first exercise
on: 
  push:
  pull_request:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: firts step
          run: |
            echo "Hello, world"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
        - name: failed step
          run: |
           echo "i will fail"
           exit 0
        - name: Say Goodbuy!
          run: |
            echo "goodbye"
        
        