name: workflow event
on: 
  push:
  pull_request:
  workflow_dispatch:
jobs:
  printevent:
    runs-on: ubuntu-latest
    steps:
      - name: event name
        run: echo "i have been triggered by an event ${{ github.event_name }}"