name: Runners
on: push
jobs:
  ubuntu-runner:
    runs-on: ubuntu-latest
    steps:
      - name: echo ubuntu os
        run: echo "The runner is $RUNNER_OS"
  windos-runner:
    runs-on: windows-latest
    steps:
      - name: echo windows os
        shell: bash
        run: echo "The runner is, ${{github.run_number}}"