name: functions expression
on:
    workflow_dispatch:
jobs:
  functions_expression:
    runs-on: ubuntu-latest
    steps:
      - name: I will fail
        run: | 
            exit 1
      - name: I will be skipped
        if: ${{ success() }}
        run: |
          echo "I will print if previous steps succeeded"
      - name: I will execute
        if: ${{ failure() }}
        run: |
         echo "i will execute if any previous step failed"
      - name: i will execute
        if: ${{ !cancelled() }}
        run: |
         echo "I will always print except when anyworkflow cancelled"
      - name: i will execute
        if: ${{cancelled()}}
        run: |
            echo "I will execute if any workflow cancelled"