name: 06-context
on:
    push:
    workflow_dispatch: 
<<<<<<< HEAD
        inputs:
          debug:
            default: false
            required: true
            type: boolean
=======
>>>>>>> parent of 7f4c60b (adding input)
jobs:
    context:
        runs-on: ubuntu-latest
        steps:
            - name: printing meta data
              run: |
                echo "Event name: ${{github.event_name}}"
                echo "Ref: ${{github.ref}}"
                echo "SHA: ${{github.sha}}"
                echo "Actor: ${{github.actor}}"
                echo "Workflow: ${{github.workflow}}"
                echo "RUNID: ${{github.run_id}}"
                echo "Run_id: ${{github.run_id}}"
                echo "Runner: ${{github.run_number}}"
            - name: retrive variable
              run : |
                    echo "variable values ${{ vars.MY_VAR }}"