name: first exercise
on: push
jobs:
  first-job:
    runs-on: ubuntu-latests
      steps:
        - name: firts step
          run: echo "Hello, world"
  second-job:
    runs-on: ubuntu-latets
      steps:
        - name: failed step
          run: |
           echo "i will fail"
           exit 1
        - name: Say Goodbuy!
          run: |
            echo "goodbye"